#!/usr/bin/env python3
"""Regenerate the dense isotropic GGX energy-complement table on a Metal device.
Uses the pinned Adobe VNDF and Smith G1 functions, 129x129 nodes (sqrt cosine),
16384 Hammersley samples/node, and exact integration of the interpolated table
for the average complement. Build consumes the checked-in artifact, not a GPU.
"""
from pathlib import Path
import subprocess
import tempfile
root=Path(__file__).resolve().parents[1]
subprocess.run(['python3',str(root/'scripts/prepare_shaders.py'),'--upstream-only'],check=True)
shader=r'''
kernel void bake_energy(device float *out [[buffer(0)]], uint2 id [[thread_position_in_grid]]) {
    if (id.x > 128 || id.y > 128) return;
    float roughness = float(id.x) / 128.0f;
    if (id.x == 0) { out[id.x*129+id.y]=0; return; }
    float cosine = max(1e-5f, pow(float(id.y)/128.0f,2.0f));
    float3 v = float3(sqrt(max(0.0f,1.0f-cosine*cosine)),0,cosine);
    float alpha=roughness*roughness, sum=0;
    for(uint i=0;i<16384;++i) {
        float2 random=float2((float(i)+0.5f)/16384.0f, float(reverse_bits(i))*2.3283064365386963e-10f);
        float3 h=openpbr_sample_aniso_ggx_smith_vndf(float2(alpha),v,random);
        float3 light=reflect(-v,h);
        float energy=light.z > 0 ? openpbr_eval_aniso_smith_g1(light,float2(alpha)) : 0;
        sum += 1.0f-energy;
    }
    out[id.x*129+id.y]=sum/16384.0f;
}
'''
swift=r'''
import Foundation
import Metal
let root=URL(fileURLWithPath:CommandLine.arguments[1])
let code=try String(contentsOf:root.appendingPathComponent("build/ShaderResources/OpenPBR.metal"),encoding:.utf8)
let extra=try String(contentsOfFile:CommandLine.arguments[2],encoding:.utf8)
guard let device=MTLCreateSystemDefaultDevice() else { fatalError("Metal GPU required") }
let opts=MTLCompileOptions();opts.mathMode = .safe
let lib=try device.makeLibrary(source:code+extra,options:opts)
let pipeline=try device.makeComputePipelineState(function:lib.makeFunction(name:"bake_energy")!)
let out=device.makeBuffer(length:129*129*4,options:.storageModeShared)!
let cb=device.makeCommandQueue()!.makeCommandBuffer()!, encoder=cb.makeComputeCommandEncoder()!
encoder.setComputePipelineState(pipeline);encoder.setBuffer(out,offset:0,index:0)
encoder.dispatchThreads(MTLSize(width:129,height:129,depth:1),threadsPerThreadgroup:MTLSize(width:8,height:8,depth:1))
encoder.endEncoding();cb.commit();cb.waitUntilCompleted()
guard cb.status == .completed else { fatalError("Energy bake failed: \(String(describing: cb.error))") }
try Data(bytes:out.contents(),count:129*129*4).write(to:URL(fileURLWithPath:CommandLine.arguments[3]))
'''
with tempfile.TemporaryDirectory(prefix='vibe-energy-') as d:
    folder=Path(d);(folder/'main.swift').write_text(swift);(folder/'bake.metal').write_text(shader)
    subprocess.run(['xcrun','swiftc','-O','-target','arm64-apple-macosx26.0',str(folder/'main.swift'),'-o',str(folder/'bake')],check=True)
    subprocess.run([str(folder/'bake'),str(root),str(folder/'bake.metal'),str(folder/'table.bin')],check=True)
    import struct
    values=struct.unpack('<'+str(129*129)+'f',(folder/'table.bin').read_bytes())
averages=[]
for r in range(129):
    row=values[r*129:(r+1)*129];integral=0.0
    for c in range(128):
        lo=c/128;hi=(c+1)/128
        slope=(row[c+1]-row[c])*128;offset=row[c]-slope*lo
        integral+=offset*(hi**4-lo**4)+0.8*slope*(hi**5-lo**5)
    averages.append(integral)
header='''// Generated by scripts/generate_metal_energy.py. Local integration adaptation.
// Adobe OpenPBR c91aad1d1ce1693e803f039d7c92c2965c4eb013; Apache-2.0.
// 129 roughness nodes x 129 sqrt-cosine nodes; 16384 Hammersley samples/node.
// Average complement exactly integrates the piecewise-linear angular table.
'''
def array(name,values):
    return 'constant float '+name+'['+str(len(values))+'] = {\n'+',\n'.join(', '.join(f'{v:.9e}f' for v in values[i:i+8]) for i in range(0,len(values),8))+'\n};\n'
code=header+array('vibeMetalEnergy',values)+array('vibeMetalAverageEnergy',averages)+'''
float vibe_metal_energy(float alpha, float cosine) {
    float x=clamp(sqrt(alpha)*128.0f,0.0f,128.0f);
    float y=sqrt(clamp(cosine,0.0f,1.0f))*128.0f;
    uint ix=min(uint(x),127u), iy=min(uint(y),127u);
    return mix(mix(vibeMetalEnergy[ix*129+iy],vibeMetalEnergy[ix*129+iy+1],y-float(iy)),
               mix(vibeMetalEnergy[(ix+1)*129+iy],vibeMetalEnergy[(ix+1)*129+iy+1],y-float(iy)),x-float(ix));
}
float vibe_metal_average_energy(float alpha) {
    float x=clamp(sqrt(alpha)*128.0f,0.0f,128.0f);
    uint ix=min(uint(x),127u);
    return mix(vibeMetalAverageEnergy[ix],vibeMetalAverageEnergy[ix+1],x-float(ix));
}
'''
(root/'Shaders/MetalEnergy.metal').write_text(code)
print('Generated dense metal energy table')
subprocess.run(['python3',str(root/'scripts/prepare_shaders.py')],check=True)
